router:
  hostname: router1
  domain: lab.test
  wan:
    mode: dhcp
    switch: "PCI 1G Port 1"
  lans:
    - name: lab
      switch: Lab-NAT
      interface: eth1
      address: 10.10.10.1/24
      dhcp:
        range: 10.10.10.100-10.10.10.200
        reservations: []
      dns:
        delegations: []
